"""Provider-neutral contracts for evidence-backed document interpretation."""

from receipt_intelligence.interpretation.contracts import (
    CandidateEntity,
    CandidateEntityReference,
    CandidateFact,
    ClassificationDimension,
    ClassificationDimensionResult,
    ClassificationOption,
    ClassificationOptionPath,
    ClassificationStatus,
    DocumentClassification,
    DocumentInterpretation,
    DocumentInterpretationRequest,
    DocumentMap,
    DocumentMapNode,
    DocumentReference,
    DocumentSource,
    EvidenceReference,
    EvidenceTextOrigin,
    InterpretationField,
    InterpretationSpecification,
    LiteralType,
    LiteralValue,
    Mention,
    NormalizationStatus,
    PageCoverage,
    PageInterpretationStatus,
    ReviewSeverity,
    ReviewSignal,
    SourcePageReference,
)
from receipt_intelligence.interpretation.validation import (
    InterpretationValidationIssue,
    InterpretationValidationIssueCode,
    InterpretationValidationResult,
    InterpretationValidationStatus,
    validate_document_interpretation,
)
from receipt_intelligence.interpretation.workflow import OnePassDocumentInterpreter

__all__ = [
    "CandidateEntity",
    "CandidateEntityReference",
    "CandidateFact",
    "ClassificationDimension",
    "ClassificationDimensionResult",
    "ClassificationOption",
    "ClassificationOptionPath",
    "ClassificationStatus",
    "DocumentClassification",
    "DocumentInterpretation",
    "DocumentInterpretationRequest",
    "DocumentMap",
    "DocumentMapNode",
    "DocumentReference",
    "DocumentSource",
    "EvidenceReference",
    "EvidenceTextOrigin",
    "InterpretationField",
    "InterpretationSpecification",
    "LiteralValue",
    "LiteralType",
    "Mention",
    "NormalizationStatus",
    "OnePassDocumentInterpreter",
    "PageCoverage",
    "PageInterpretationStatus",
    "InterpretationValidationIssue",
    "InterpretationValidationIssueCode",
    "InterpretationValidationResult",
    "InterpretationValidationStatus",
    "ReviewSeverity",
    "ReviewSignal",
    "SourcePageReference",
    "validate_document_interpretation",
]
