"""Provider-neutral contracts for evidence-backed document interpretation."""

from receipt_intelligence.interpretation.contracts import (
    CandidateEntity,
    CandidateEntityReference,
    CandidateFact,
    ClassificationDimension,
    ClassificationDimensionResult,
    ClassificationOption,
    ClassificationOptionPath,
    ClassificationStatus,
    DocumentClassification,
    DocumentInterpretation,
    DocumentInterpretationOutcome,
    DocumentInterpretationRequest,
    DocumentInterpretationValidation,
    DocumentMap,
    DocumentMapNode,
    DocumentReference,
    DocumentSource,
    EvidenceReference,
    EvidenceTextProvenance,
    InterpretationField,
    InterpretationSpecification,
    InterpretationValidationStatus,
    LiteralType,
    LiteralValue,
    Mention,
    NormalizationStatus,
    PageHandlingState,
    ReviewSeverity,
    ReviewSignal,
    SourcePageHandling,
    SourcePageRange,
    SourcePageReference,
    ValidationIssue,
)
from receipt_intelligence.interpretation.validation import validate_document_interpretation
from receipt_intelligence.interpretation.workflow import OnePassDocumentInterpreter

__all__ = [
    "CandidateEntity",
    "CandidateEntityReference",
    "CandidateFact",
    "ClassificationDimension",
    "ClassificationDimensionResult",
    "ClassificationOption",
    "ClassificationOptionPath",
    "ClassificationStatus",
    "DocumentClassification",
    "DocumentInterpretation",
    "DocumentInterpretationOutcome",
    "DocumentInterpretationRequest",
    "DocumentInterpretationValidation",
    "DocumentMap",
    "DocumentMapNode",
    "DocumentReference",
    "DocumentSource",
    "EvidenceReference",
    "EvidenceTextProvenance",
    "InterpretationField",
    "InterpretationSpecification",
    "InterpretationValidationStatus",
    "LiteralValue",
    "LiteralType",
    "Mention",
    "NormalizationStatus",
    "OnePassDocumentInterpreter",
    "PageHandlingState",
    "ReviewSeverity",
    "ReviewSignal",
    "SourcePageHandling",
    "SourcePageRange",
    "SourcePageReference",
    "ValidationIssue",
    "validate_document_interpretation",
]
